### ISSUE TITLE
does it have a theme for github

### ISSUE THREAD

**Issue by gek169** [dracula/dracula-theme#589] opened 2021-06-28 03:45 UTC
can I use dracula theme for github itself

if so does that make dracula theme self-hosting?

**Comment by Thokya** [comment] 2021-06-29 06:03
I have the same question I cannot seem to  find any dracula theme for github

**Comment by bigpick** [comment] 2021-07-15 12:37
By _Github itself_, you mean like just in general github.com/pages? (and not github pages or something else?)

If so, no. Github does not officially support custom color schemes, so there is no way for Dracula to offer an official scheme for Github. You'd have to use one of the four official Github themes to change the look of the site itself officially.

.... unofficially, you would have to try one of the plugins/tools that recolors all of your internet browsing (Darkreader, Nighteye, Midnight lizard, etc... I don't use these so apologies if I missed the 'popular' ones)
* There is some Dracula discussion around Darkreader content [here](https://github.com/dracula/dracula-theme/issues/382).
* There is a new theme request/implementation for Midnight Lizard [here](https://github.com/dracula/dracula-theme/issues/309).

**Comment by bigpick** [comment] 2021-07-15 12:42
Going to close this as a dupe of https://github.com/dracula/dracula-theme/issues/392 for now; also, as Ben suggests there, if you find a different plugin that is doing recoloring and they support pygments, you could also just use the Dracula values for that as well.

**Closed by bigpick** 2021-07-15 12:42 UTC

**Comment by gek169** [comment] 2021-07-16 00:09
thanks

**Comment by wasi-master** [comment] 2021-11-25 05:38
You can use the [Chrome](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en)/[Firefox](https://addons.mozilla.org/en-US/firefox/addon/stylish/) extension called [Stylish](https://en.wikipedia.org/wiki/Stylish) and just use the css from the pygments theme, https://github.com/dracula/pygments/blob/master/dracula.css

You'll have to change the background color selector though

**Comment by zenorocha** [comment] 2022-01-18 06:31
https://draculatheme.com/github 💥

**Comment by wasi-master** [comment] 2022-01-18 06:34
Cool
