### ISSUE TITLE
Syntax Highlighting for each language...

### ISSUE THREAD

**Issue by rediffusion** [dracula/dracula-theme#362] opened 2020-01-04 22:41 UTC
## About Syntax.

 First of all th10 for an awesome theme! 🎆
I don't understand why the color syntax for all languages that I use (i.e. - C#, JS, TS, AHK, C++, C, Java, Html, CSS, Python...) is the same?
 Is there a wat to implement for ich language his own different ⚡`Syntax Highlighting`⚡ ?

Regards! 👍✌️

**Comment by benknoble** [comment] 2020-01-05 15:55
Couple of notes about the idea:

- wouldn’t it be jarring to have languages use different colors?
- this depends heavily on your editor/program: in vim, the colorscheme is global (but syntax matches can be adjusted individually)
- the point of having a single, somewhat standardized colors is to unify colors, IMO

**Comment by rediffusion** [comment] 2020-01-07 05:41
0Key, my friend let me explain it another way...

As an example, I'll take the IDE called «[NotePad++](https://notepad-plus-plus.org/downloads/)».
I have a theme called "Plastic Code Wrap". It looks like this:

![image](https://user-images.githubusercontent.com/30071027/71870673-e2fdf080-3127-11ea-8c28-428853d86fee.png)

Now I put here some `code`, then I switch to other languages...

## C#

![image](https://user-images.githubusercontent.com/30071027/71870861-5a338480-3128-11ea-8f6e-cd5d191ade4f.png)

## JavaScript

![image](https://user-images.githubusercontent.com/30071027/71870894-79321680-3128-11ea-83cb-26d711905f0b.png)

## AutoHotkey

![image](https://user-images.githubusercontent.com/30071027/71870922-94048b00-3128-11ea-9bb0-88cf003a5864.png)

## C++

![image](https://user-images.githubusercontent.com/30071027/71870945-a8e11e80-3128-11ea-8b35-b84e162f0b6f.png)

## CSS

![image](https://user-images.githubusercontent.com/30071027/71870978-c57d5680-3128-11ea-9c90-c90aa3fe5a69.png)

## HTML 

![image](https://user-images.githubusercontent.com/30071027/71870995-d29a4580-3128-11ea-864e-8311edc3ce87.png)

Different syntax, color, style, font, weight, brackets... etc.
But in your cool **theme** I see the same shit with all languages. Please help! 🙏

**Comment by benknoble** [comment] 2020-01-07 20:41
You're trying to highlight invalid HTML/CSS/JS, so it's not "different color" it's just *wrong*. Code highlighting is (often) going to be broken if the code isn't valid. So I'm still not sure I see your point.

**Comment by rediffusion** [comment] 2020-01-07 22:29
@benknoble 

💡 _0K I got you!_ 
 There's a code googled for each language. Now every language has his code.
And yes I wanna tell you that "Syntax Highlighting" is different for ich language.

I've updated the screenshot bottom, please take a look.  👁️🔍

With regards! ✌️

**Comment by zenorocha** [comment] 2020-01-07 22:33
Here's an idea - if you're looking to create your own theme and you're wondering how we made it, why don't you fork our code and build your theme on top of that?

Here's the source code: https://github.com/dracula/notepad-plus-plus

Since this is not a bug, I'll go ahead and close it, ok?

Thanks!

**Closed by zenorocha** 2020-01-07 22:33 UTC

**Comment by rediffusion** [comment] 2020-01-07 22:35
@zenorocha 

As you wish!
