### ISSUE TITLE
Dracula for Eclipse

### ISSUE THREAD

**Issue by namitoyokota** [dracula/dracula-theme#327] opened 2019-06-28 21:21 UTC
## New Theme?

We would love to support all code editors out there, but we need your help to accomplish that. Feel free to create a new theme based on our [color palette](https://github.com/dracula/dracula-theme#color-palette).

## Existing Theme?

Consider fixing the issue yourself. That's the best way to contribute ;)

If that doesn't work, take a screenshot that shows the actual bug and mention the [specific maintainer](https://github.com/dracula/dracula-theme#team) of your theme.

**Comment by hacknug** [comment] 2019-06-29 15:52
Duplicate of #29

**Closed by hacknug** 2019-06-29 15:52 UTC
Labels: new-theme-request
